# version: "3.8"

# services:
#   langchain-app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: langchain-rag
#     ports:
#       - "8501:8501"
#     environment:
#       - OLLAMA_BASE_URL=http://host.docker.internal:11434
#     extra_hosts:
#       - "host.docker.internal:host-gateway"
#     restart: unless-stopped



# ✅ docker-compose.yml - 전체 실행 자동화
version: '3.8'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: langchain-streamlit
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: []
    restart: unless-stopped

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: langchain-api
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: []
    restart: unless-stopped